### ISSUE TITLE
Audio removal issue

### ISSUE THREAD

**Issue by foremtehan** [Kurtnoise-zeus/megui#16]
![image](https://github.com/user-attachments/assets/cc1429b8-8474-4e28-a0ea-c2979f171fcb)

i'm using 6666.2308 x64, when i remove audio track from One click Encoder i got this error

**Comment by Kurtnoise-zeus** [comment]
Hi, 

Why not using the latest release instead ? https://github.com/Kurtnoise-zeus/megui/releases

**Comment by foremtehan** [comment]
```
--[Information] [1/1/2025 8:56:56 PM] Exception message: Object reference not set to an instance of an object.
-[NoImage]    at MeGUI.OneClickWindow.audioTab_SelectedIndexChanged(Object sender, EventArgs e) in E:\megui\packages\tools\oneclick\OneClickWindow.cs:line 2274
-[NoImage]    at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
-[NoImage]    at System.Windows.Forms.TabControl.WmSelChange()
-[NoImage]    at System.Windows.Forms.TabControl.set_SelectedIndex(Int32 value)
-[NoImage]    at MeGUI.OneClickWindow.AudioRemoveTrack(Int32 iTabPageIndex) in E:\megui\packages\tools\oneclick\OneClickWindow.cs:line 2046
-[NoImage]    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
-[NoImage]    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
-[NoImage]    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
-[NoImage]    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
-[NoImage]    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
-[NoImage]    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
-[NoImage]    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
-[NoImage]    at System.Windows.Forms.Control.WndProc(Message& m)
-[NoImage]    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
-[NoImage]    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
-[NoImage]    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
--[Information] [1/1/2025 8:56:56 PM] Stacktrace
--[Information] [1/1/2025 8:56:56 PM] Inner exception: null
```

**Comment by Kurtnoise-zeus** [comment]
this is coming from the latest release or still the old one ?

**Comment by Kurtnoise-zeus** [comment]
Closed issue without more information. Try to provide more in order to debug.
